spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/library_db
    password: DORIME
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: validate
    show-sql: 'false'
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: electroniclibrarysystem@gmail.com
    password: "vunnlgtmtrhaearf"
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      database: library_db
springdoc:
  swagger-ui:
    path: api
server:
  port: 8081
